# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check --fix
        stages: [pre-merge-commit, pre-push]
        language: python
        types: [python, pyi]
        require_serial: true
        minimum_pre_commit_version: "2.9.2"
      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: python
        types: [python, pyi]
        require_serial: true
        minimum_pre_commit_version: "2.9.2"
      - id: prettier
        name: prettier
        entry: npx prettier --write
        language: node
        types: [javascript, json, markdown, yaml, toml]
        exclude: |
          (?x)(
            ^node_modules/|
            ^dist/|
            ^build/|
            ^.pytest_cache/|
            ^.ruff_cache/|
            \.pyc$|
            \.vsmeta$|
            \.pdf$|
            \.txt$
          )
        require_serial: true
        minimum_pre_commit_version: "2.9.2"
      - id: eslint
        name: eslint
        entry: npx eslint --fix
        language: node
        types: [javascript]
        require_serial: true
        minimum_pre_commit_version: "2.9.2"
